/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Utils.DatabaseUtils;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import models.Product;

/**
 *
 * @author ISHAQ
 */
public class CreateForm extends javax.swing.JPanel {

    /**
     * Creates new form CreateForm
     */
    
    JSplitPane splitPane;
    JPanel bottomPanel;
    public CreateForm(JPanel bottomPanel, JSplitPane splitPane) {
        this.bottomPanel = bottomPanel;
        this.splitPane = splitPane;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        tbnInsert = new javax.swing.JButton();
        btnViewPanel = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Name of product:");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Price of product:");

        txtName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtPrice.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tbnInsert.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tbnInsert.setText("Insert product into Db");
        tbnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnInsertActionPerformed(evt);
            }
        });

        btnViewPanel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnViewPanel.setText("Visit product details page");
        btnViewPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(tbnInsert)))
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tbnInsert)
                .addGap(18, 18, 18)
                .addComponent(btnViewPanel)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnInsertActionPerformed
        // TODO add your handling code here:
        if (txtName.getText().isBlank() || txtPrice.getText().isBlank()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please Enter Value in both textfields!", "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            if (DatabaseUtils.insertProduct(new Product(txtName.getText().trim(), 
                    Double.parseDouble(txtPrice.getText().trim())))) {
                JOptionPane.showMessageDialog(
                        this,
                        "product Inserted into the Database!", "Done", JOptionPane.INFORMATION_MESSAGE);
                txtName.setText("");
                txtPrice.setText("");
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "There was an error in the operation!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tbnInsertActionPerformed

    private void btnViewPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPanelActionPerformed
        // TODO add your handling code here:
        javax.swing.JLabel titleLabel = (javax.swing.JLabel)splitPane.getTopComponent();
        ViewForm display = new ViewForm(bottomPanel, titleLabel);
        bottomPanel.add(display);
        CardLayout cl = (CardLayout) bottomPanel.getLayout();
        titleLabel.setText("PRODUCT DETAILS PAGE");
        cl.next(bottomPanel);
        
    }//GEN-LAST:event_btnViewPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton tbnInsert;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
